name: Continuous Integration (CI)

on:
  push:

jobs:
  build-ios-app:
    name: Build (ios)
    runs-on: macos-latest
    env:
      XC_SCHEME: ${{ 'doberman' }}
      XC_CONFIGURATION: ${{ 'Release' }}
      XC_WORKSPACE: ${{ 'ios/doberman.xcworkspace' }}
      XC_DESTINATION: ${{ 'generic/platform=iOS' }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node.js v18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm install && npm run install:ios

      - name: Build the iOS archive
        run: |
            xcodebuild \
              archive \
              -workspace "$XC_WORKSPACE" \
              -configuration "$XC_CONFIGURATION" \
              -scheme "$XC_SCHEME" \
              -destination "$XC_DESTINATION"
