name: On Dependency Update
# description: Triggers an update to the app's caches when a dependency list changes.

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      # Run only if one of these files have changed
      - "package-lock.json"
      - "ios/Podfile.lock"
      - "Gemfile.lock"
      - ".github/workflows/on-dependency-update.yml"
      - ".github/actions/install-dependencies/action.yml"

jobs:
  rebuild-android-cache:
    name: Rebuild Android Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rebuild cache
        uses: ./.github/actions/install-dependencies

  rebuild-ios-cache:
    name: Rebuild iOS Cache
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rebuild cache
        uses: ./.github/actions/install-dependencies
